export default [
	{ name: "accessibility", keyword: "other" },
	{ name: "adding a test", keyword: "test" },
	{ name: "code review changes", keyword: "build" },
	{ name: "animations and transitions", keyword: "other" },
	{ name: "bugfix", keyword: "fix" },
	{ name: "comments", keyword: "docs" },
	{ name: "initial commit", keyword: "init" },
	{ name: "configuration", keyword: "chore" },
	{ name: "deploy", keyword: "other" },
	{ name: "documentation", keyword: "docs" },
	{ name: "in progress", keyword: "other" },
	{ name: "interface styling", keyword: "feat" },
	{ name: "infrastructure", keyword: "ci" },
	{ name: "tasks", keyword: "other" },
	{ name: "move/rename", keyword: "chore" },
	{ name: "new feature", keyword: "feat" },
	{ name: "package.json", keyword: "build" },
	{ name: "performance", keyword: "perf" },
	{ name: "refactoring", keyword: "refactor" },
	{ name: "deleting a file", keyword: "other" },
	{ name: "removing a dependency", keyword: "build" },
	{ name: "responsivity", keyword: "other" },
	{ name: "reverting changes", keyword: "fix" },
	{ name: "security", keyword: "other" },
	{ name: "SEO", keyword: "other" },
	{ name: "version tag", keyword: "other" },
	{ name: "passing test", keyword: "test" },
	{ name: "tests", keyword: "test" },
	{ name: "text", keyword: "other" },
	{ name: "typing", keyword: "other" },
	{ name: "error handling", keyword: "other" },
];
